WIP filters experiments.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -13,25 +13,34 @@ ROOT=$(dirname "$0")/..
 
 mkdir -p "$DST"
 
-status "Rendering"
 shopt -s globstar
-for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
-  # Strip `src` path from file string
-  FROM="${file##$SRC}"
-  # Define a target file with the new extension
-  TO="${FROM%%$SRC_EXT}$DST_EXT"
-  echo "$FROM --> $TO"
-  mkdir -p "$(dirname "$DST$TO")"
-  # shellcheck disable=SC2086
-  pandoc $PANOPTS $file --output=$DST$TO || warn "Failed to create $TO"
-done
+status "Markup-generation"
 
-status "Copying over assets"
-for file in "$STATIC"/{,**/}*.*; do
-  FROM=$file
-  TO="$DST${file##$STATIC}"
-  echo "${FROM##$ROOT} --> ${TO##$ROOT}"
-  mkdir -p "$(dirname "$TO")"
-  cp "$FROM" "$TO" || warn "Failed to copy asset $TO"
-done
+if ! python3 -c "import panflute" > /dev/null 2>&1; then
+  pip3 --disable-pip-version-check install panflute
+fi
+
+pandoc "$SRC"/{,**/}*."$SRC_EXT" --filter bin/zettel_map.py -t markdown_github --output testfile
+# pandoc "$SRC"/{,**/}*."$SRC_EXT" -f markdown_github -t native --output ast
+
+#status "Rendering"
+#for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
+#  # Strip `src` path from file string
+#  FROM="${file##$SRC}"
+#  # Define a target file with the new extension
+#  TO="${FROM%%$SRC_EXT}$DST_EXT"
+#  echo "$FROM --> $TO"
+#  mkdir -p "$(dirname "$DST$TO")"
+#  # shellcheck disable=SC2086
+#  pandoc $PANOPTS $file --output=$DST$TO || warn "Failed to create $TO"
+#done
+#
+#status "Copying over assets"
+#for file in "$STATIC"/{,**/}*.*; do
+#  FROM=$file
+#  TO="$DST${file##$STATIC}"
+#  echo "${FROM##$ROOT} --> ${TO##$ROOT}"
+#  mkdir -p "$(dirname "$TO")"
+#  cp "$FROM" "$TO" || warn "Failed to copy asset $TO"
+#done
 shopt -u globstar
