fixed typo in warning

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -25,7 +25,7 @@ do
    TO="${FROM%%$SRC_EXT}$DST_EXT"
    echo "$FROM --> $TO"
    mkdir -p $(dirname "$DST$TO")
-   pandoc $PANOPTS --output=$DST$TO $file || warn "failed TO create $TO"
+   pandoc $PANOPTS --output=$DST$TO $file || warn "failed to create $TO"
 done
 
 status "Copying over assets"
@@ -35,5 +35,5 @@ do
     TO="$DST${file##$SRC}"
     echo "${FROM##$ROOT} --> ${TO##$ROOT}"
     mkdir -p $(dirname $TO)
-    cp $FROM $TO || warm "Failed TO copy asset $TO"
+    cp $FROM $TO || warm "Failed to copy asset $TO"
 done
