Build is parallel and re-written for `bin/sh`. (#95)
* Build is parallel and re-written for `bin/sh`.

With a bit of help from ChatGPT, I was able to make my rendering script faster. Now that it's in shell and not bash, color printing works!

* Simpler way to loop over files with `find`.

* Added wait to do work in stages.

* Added log statements back from rendering.

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,11 +1,11 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 #
 # Invoke pandoc on $SRC, copy $STATIC assets over to $DST.
 #
 
 set -e
 
-ROOT=$(dirname "$(dirname "$(realpath "$0")")")
+ROOT=$(dirname "$(dirname "$0")")
 # shellcheck source=bin/env
 . "$ROOT"/bin/env
 # shellcheck source=bin/logging
@@ -13,9 +13,8 @@ ROOT=$(dirname "$(dirname "$(realpath "$0")")")
 
 mkdir -p "$DST"
 
-status "Rendering"
-shopt -s globstar
-for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
+convert() {
+  file="$1"
   # Strip `src` path from file string
   FROM="${file##"$SRC"}"
 
@@ -24,8 +23,8 @@ for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
   #  src/some/path/index.md   --> public/some/path/index.html
   # In order words: Let the file name become the slug name
   # and let any index page simply become an index.hml page.
-  filename=${FROM##*/}
-  if [[ "$filename" =~ index\.md$ ]]; then
+  filename=$(basename "$FROM")
+  if echo "$filename" | grep -q 'index\.md$'; then
     TO="${FROM%%"$SRC_EXT"}$DST_EXT"
   else
     TO="${FROM%%".$SRC_EXT"}/index.$DST_EXT"
@@ -34,18 +33,29 @@ for file in "$SRC"/{,**/}*."${SRC_EXT}"; do
   echo "$FROM --> $TO"
   mkdir -p "$(dirname "$DST$TO")"
   # shellcheck disable=SC2086
-  pandoc $PANOPTS $file --output=$DST$TO || warn "Failed to create $TO"
-done
+  pandoc $PANOPTS "$file" --output="$DST$TO" || warn "Failed to create $TO"
+}
 
-status "Copying over assets"
-for file in "$STATIC"/{,**/}*.*; do
+copy() {
+  file="$1"
   FROM=$file
   TO="$DST${file##"$STATIC"}"
   echo "${FROM##"$ROOT"} --> ${TO##"$ROOT"}"
   mkdir -p "$(dirname "$TO")"
   cp "$FROM" "$TO" || warn "Failed to copy asset $TO"
+}
+
+status "Rendering"
+find "$SRC" -type f -name "*.$SRC_EXT" | while IFS= read -r file; do
+  convert "$file" &
 done
-shopt -u globstar
+wait
+
+status "Copying over assets"
+find "$STATIC" -type f | while IFS= read -r file; do
+  copy "$file" &
+done
+wait
 
 status "Rendering RSS feed"
 # This does the following:
